server:
  port: 8888 #修改springboot内置服务器默认端口号
  #配置jsp视图解析器
spring:
  mvc:
    view:
      prefix: /
      suffix: .jsp
      #配置连接数据源
  datasource:
    type: org.apache.commons.dbcp.BasicDataSource
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/sm

mybatis:
  mapper-locations: classpath:com/baizhi/mapper/*xml
  #指定起别名的类
  type-aliases-package: com.baizhi.entity

